# Generated by Django 5.2.5 on 2025-08-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardGamePlayerItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardGameHistoryItem',
            fields=[
                ('game_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('game_context', models.JSONField(default=dict)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_a', to='db.cardgameplayeritem')),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_b', to='db.cardgameplayeritem')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='db.cardgameplayeritem')),
            ],
        ),
    ]
